#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const sidecar = path.resolve(dir, "../go-watcher")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const offline = process.argv.includes("--offline") || process.env.OPENCODE_OFFLINE === "1"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`)
      .then((x) => x.text())
      .catch((err) => {
        if (!offline && process.platform !== "win32") throw err
        return ""
      })
if (modelsData) {
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.js"),
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
} else {
  console.log("Using existing models-snapshot.js")
}

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const skipWeb = process.argv.includes("--skip-web")
const skipSmoke = process.argv.includes("--skip-smoke")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

function goname(item: { os: string; arch: "arm64" | "x64" }) {
  const arch = item.arch === "x64" ? "amd64" : "arm64"
  const file = item.os === "win32" ? "opencode-watcher.exe" : "opencode-watcher"
  const os = item.os === "win32" ? "windows" : item.os
  return { arch, file, os }
}

async function watcher(item: { os: string; arch: "arm64" | "x64" }, out: string) {
  const go = goname(item)
  fs.mkdirSync(path.dirname(out), { recursive: true })
  console.log(`building go watcher for ${go.os}-${go.arch}`)
  await $`CGO_ENABLED=0 GOOS=${go.os} GOARCH=${go.arch} go build -ldflags="-s -w" -o ${out} ./cmd/opencode-watcher`.cwd(sidecar)
}

fs.rmSync("dist", { recursive: true, force: true })

// Sync version into package.json so the web app picks it up at build time
const pkgPath = path.resolve(dir, "package.json")
const pkgRaw = await Bun.file(pkgPath).json()
const originalVersion = pkgRaw.version
pkgRaw.version = Script.version
await Bun.write(pkgPath, JSON.stringify(pkgRaw, null, 2) + "\n")

// Build web app (packages/app) and embed alongside binary
const base = process.env.VITE_BASE_PATH
try {
  if (!skipWeb) {
    console.log("building web app...")
    process.env.VITE_BASE_PATH = "./"
    await $`bun run --cwd ${path.resolve(dir, "../../packages/app")} build`
    console.log("web app built")
  }
} finally {
  if (base === undefined) {
    delete process.env.VITE_BASE_PATH
  } else {
    process.env.VITE_BASE_PATH = base
  }
  // Restore original version in package.json to avoid dirtying the working tree
  pkgRaw.version = originalVersion
  await Bun.write(pkgPath, JSON.stringify(pkgRaw, null, 2) + "\n")
}

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  fs.mkdirSync(`dist/${name}/bin`, { recursive: true })
  await watcher(item, path.resolve(dir, `dist/${name}/bin/native/${goname(item).file}`))

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/aether`,
      execArgv: [`--user-agent=aether/${Script.version}`, "--use-system-ca", "--"],
      windows: {
        description: "Aether",
        title: "Aether",
        publisher: "Science Discovery",
        version: Script.version,
      },
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  // Smoke test: only run if binary is for current platform
  if (!skipSmoke && item.os === process.platform && item.arch === process.arch && !item.abi) {
    const binaryPath = `dist/${name}/bin/aether`
    console.log(`Running smoke test: ${binaryPath} --version`)
    try {
      const versionOutput = await $`${binaryPath} --version`.text()
      console.log(`Smoke test passed: ${versionOutput.trim()}`)
    } catch (e) {
      console.error(`Smoke test failed for ${name}:`, e)
      process.exit(1)
    }
  }

  fs.rmSync(`dist/${name}/bin/tui`, { recursive: true, force: true })

  // Copy web assets next to the binary
  fs.cpSync(path.resolve(dir, "../../packages/app/dist"), `dist/${name}/bin/web`, { recursive: true })

  // Copy default skills next to the binary so they are available without a project config
  const skillsSrc = path.resolve(dir, "../../.opencode/skills")
  if (fs.existsSync(skillsSrc)) {
    fs.cpSync(skillsSrc, `dist/${name}/bin/.opencode/skills`, { recursive: true })
  }

  // Copy wechat-bridge resources
  const wechatBridgeSrc = path.resolve(dir, "../../Aether-wechat-bridge")
  if (fs.existsSync(wechatBridgeSrc)) {
    fs.cpSync(wechatBridgeSrc, `dist/${name}/bin/wechat-bridge`, {
      recursive: true,
      filter: (src) => !src.includes("__pycache__") && !src.includes(".venv"),
    })

    // 只保留当前目标平台的 uv 二进制，删除其他平台的
    const uvDir = `dist/${name}/bin/wechat-bridge/runtime/uv`
    if (fs.existsSync(uvDir)) {
      const uvTarget =
        item.os === "darwin" && item.arch === "arm64"
          ? "aarch64-apple-darwin"
          : item.os === "darwin"
            ? "x86_64-apple-darwin"
            : item.os === "win32"
              ? "x86_64-pc-windows-msvc"
              : item.arch === "arm64"
                ? "aarch64-unknown-linux-gnu"
                : "x86_64-unknown-linux-gnu"

      for (const entry of fs.readdirSync(uvDir)) {
        const entryPath = path.join(uvDir, entry)
        if (fs.statSync(entryPath).isDirectory() && !entry.includes(uvTarget)) {
          fs.rmSync(entryPath, { recursive: true })
        }
      }
    }
  }

  // Copy launcher
  if (item.os === "win32") {
    fs.copyFileSync(path.resolve(dir, "launcher/Aether.vbs"), `dist/${name}/bin/Aether.vbs`)
    const phDest = `dist/${name}/bin/aether-protocol-handler.vbs`
    fs.copyFileSync(path.resolve(dir, "launcher/aether-protocol-handler.vbs"), phDest)
  } else if (item.os === "darwin") {
    const dest = `dist/${name}/bin/Aether.command`
    fs.copyFileSync(path.resolve(dir, "launcher/Aether.command"), dest)
    fs.chmodSync(dest, 0o755)
  } else if (item.os === "linux") {
    const dest = `dist/${name}/bin/Aether.sh`
    fs.copyFileSync(path.resolve(dir, "launcher/Aether.sh"), dest)
    fs.chmodSync(dest, 0o755)
    const phDest = `dist/${name}/bin/aether-protocol-handler.sh`
    fs.copyFileSync(path.resolve(dir, "launcher/aether-protocol-handler.sh"), phDest)
    fs.chmodSync(phDest, 0o755)
  }

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
